### ISSUE TITLE
Weekdays as string

### ISSUE THREAD

**Issue by hperrey** [jonathondown89/clock#3]
If you want to deal with weekdays as strings, you could have a simple workaround: create a list of weekdays and access the member by index:
```
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
print(f'Today is {weekdays[now.weekday()]}')
```

https://github.com/jonathondown89/clock/blob/8c4fcf6a94a28a0cc02087cfc17c2bb67e63ad3f/clock_project.py#L20

**Comment by jonathondown89** [comment]
Thanks! I altered the format to read clearer for the user; 

from datetime import datetime
now = datetime.now()

value =input("What is your name? ") #name input
print("Cool...Hello there!")

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

str1=("%02d/%02d/%04d" % (now.day, now.month, now.year))
str2=(""" and the exact time is %02d:%02d:%02d.""" % (now.hour, now.minute, now.second))
print(f'Today is {weekdays[now.weekday()]}','the',str1 + str2)
